# Basic
title: Fengshiwest's GitHub Homepage
subtitle: 山水一程 三生有幸
#welcome_message: <a href="https://github.com/fengshiwest/fengshiwest.github.io" target="_blank">My blog</a>
description: fengshiwest is a student from Wuhan University, majoring in Software Engineering.
creator: <a href="https://github.com/fengshiwest/">@fengshiwest</a>

url: "https://github.com/fengshiwest/fengshiwest.github.io"
comments: true
permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/fengshiwest/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: fengshiwest
    # duoshuo: 
    
# Social
social:
    #weibo: JoanWood
    github: fengshiwest
    mail: fengshiwest@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
